"""Minimal constants needed for Vector XL Driver Library LIN control."""

XL_SUCCESS = 0
XL_ERR_QUEUE_IS_EMPTY = 10

XL_INTERFACE_VERSION_V3 = 3
XL_INTERFACE_VERSION = XL_INTERFACE_VERSION_V3

XL_INVALID_PORTHANDLE = -1

XL_BUS_TYPE_NONE = 0x00000000
XL_BUS_TYPE_LIN = 0x00000002

XL_ACTIVATE_NONE = 0
XL_ACTIVATE_RESET_CLOCK = 8

XL_LIN_MASTER = 0x01
XL_LIN_SLAVE = 0x02

XL_LIN_VERSION_1_3 = 0x01
XL_LIN_VERSION_2_0 = 0x02
XL_LIN_VERSION_2_1 = 0x03

XL_LIN_CALC_CHECKSUM = 0x100
XL_LIN_CALC_CHECKSUM_ENHANCED = 0x200

XL_LIN_CHECKSUM_CLASSIC = 0x00
XL_LIN_CHECKSUM_ENHANCED = 0x01
XL_LIN_CHECKSUM_UNDEFINED = 0xFF

XL_LIN_UNDEFINED_DLC = 0xFF

XL_LIN_MSGFLAG_TX = 0x40
XL_LIN_MSGFLAG_CRCERROR = 0x81

XL_LIN_MSG = 20
XL_LIN_ERRMSG = 21
XL_LIN_SYNCERR = 22
XL_LIN_NOANS = 23
XL_LIN_WAKEUP = 24
XL_LIN_SLEEP = 25
XL_LIN_CRCINFO = 26

LIN_VERSION_BY_NAME = {
    "1.3": XL_LIN_VERSION_1_3,
    "2.0": XL_LIN_VERSION_2_0,
    "2.1": XL_LIN_VERSION_2_1,
}

LIN_VERSION_NAME_BY_VALUE = {value: key for key, value in LIN_VERSION_BY_NAME.items()}

CHECKSUM_BY_NAME = {
    "classic": XL_LIN_CHECKSUM_CLASSIC,
    "enhanced": XL_LIN_CHECKSUM_ENHANCED,
    "undefined": XL_LIN_CHECKSUM_UNDEFINED,
}

EVENT_NAMES = {
    XL_LIN_MSG: "XL_LIN_MSG",
    XL_LIN_ERRMSG: "XL_LIN_ERRMSG",
    XL_LIN_SYNCERR: "XL_LIN_SYNCERR",
    XL_LIN_NOANS: "XL_LIN_NOANS",
    XL_LIN_WAKEUP: "XL_LIN_WAKEUP",
    XL_LIN_SLEEP: "XL_LIN_SLEEP",
    XL_LIN_CRCINFO: "XL_LIN_CRCINFO",
}
